spring:
  application:
    name: crawler_redfin
  data:
    mongodb:
      host: 10.54.16.68
      database: redfin_data
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    prometheus:
      enabled: true
      

